Repository EnigmaVSSUT/Induction-2021, pull requests merged in 2021-05, with the labels that each got.

#98 mangat-hansdah.txt
  Open Source/Git1/mangat-hansdah.txt
  Open Source/Git2/mangathansdah.jpg
Labels: Task 2, completed

#237 Task2
  Open Source/Git2/Om-Satpathy.jfif
Labels: Task 2, completed

#235 add task-1 and task-2 assignment
  Open Source/Git1/Raman-Agarwal.txt
  Open Source/Git2/Raman-Agarwal.jpg
Labels: Task 2, completed

#234 task 1
  Open Source/Git1/Ayush-Nayak.txt
  Open Source/Git2/Ayush-Nayak.jpg
Labels: Task 2, completed

#232 Task 2 Completed
  Open Source/Git2/Subham-dash.jpg
Labels: Task 2, completed

#231 Task - 2 Completed
  Open Source/Git2/Ashutosh.jpg
Labels: Task 2, completed

#230 task 2
  Open Source/Git2/sachhidananda.jpeg
Labels: Task 2, completed

#229 Arpita Panda PR
  Open Source/Git1/Arpita-Panda.txt
Labels: Task 1, completed

#227 Task 2 completed
  Open Source/Git2/om-parmar.jpg
Labels: Task 2, completed

#224 Task 2
  Open Source/Git1/Abhaya-padhi.txt
  Open Source/Git2/Abhaya-Padhi.jpg
Labels: Task 2, completed

#223 added new image
  Open Source/Git2/Sourav-Samal.jfif
Labels: Task 2, completed

#222 added a new image
  Open Source/Git2/yash-jain.jfif
Labels: Task 2, completed

#218 Induction Task 1&2
  Open Source/Git1/Adarsh-Goswami.txt
  Open Source/Git2/Adarsh-Goswami.jpg
Labels: Task 2, completed

#216 task 2
  Open Source/Git2/Swaraj-Pradhan.jpg
Labels: Task 2, completed

#215 Task 1
  Open Source/Git1/Tanisha_Mohanta.txt
  Open Source/Git2/TanishaMohanta.jpg
Labels: Task 2, completed

#213 task 2
  Open Source/Git2/Pramit-Singh.jpg
Labels: Task 2, completed

#212 Task 2 Completed
  Open Source/Git2/Gayatri-Padhi.jpg
Labels: Task 2, completed

#211 task 2
  Open Source/Git2/Astha-Niharika.jpg
Labels: Task 2, completed

#210 Task2
  Open Source/Git2/Sangram-Subudhi.jpg
Labels: Task 2, completed

#206 Shashwati-Panda.jpg
  Open Source/Git2/Shashwati-Panda.jpg
Labels: Task 2, completed

#205 Task 2 completed
  Open Source/Git1/Laxmi-Bariha.txt
  Open Source/Git2/Laxmi-Bariha.jpg
Labels: Task 2, completed

#204 Task2
  Open Source/Git2/shubham-panigrahi.jfif
Labels: Task 2, completed

#203 Task
  Open Source/Git1/Arabinda Sahoo.txt
Labels: Task 1, completed

#202 SWAPNIL'S TASK-2
  Open Source/Git2/SWAPNIL-KUMAR-SAHU.jpg
Labels: Task 2, completed

#201 task 2-complete
  Open Source/Git2/sushobhan-biswal.jfif
Labels: Task 2, completed

#199 photo added
  Open Source/Git2/satyajeet-tripathy.jpg
Labels: Task 2, completed

#198 Task 2 complete
  Open Source/Git2/sidhharthchandandalai.jpg
Labels: Task 2, completed

#196 Image Added
  Open Source/Git2/Lopamudra-Behera.jpg
Labels: Task 2, completed

#195 Create Swati Rath.jpg
  Open Source/Git2/Swati Rath.jpg
Labels: Task 2, completed

#191 Task 2 Completed
  Open Source/Git2/Adyasha-Samal.png
Labels: Task 2, completed

#190 Task-2
  Open Source/Git2/Tanusriya.jfif
Labels: Task 2, completed

#189 Task 2 done
  Open Source/Git2/Subhasis-Gouda.jpg
Labels: Task 2, completed

#188 task 2
  Open Source/Git2/Sweta_Padhy.jpg
Labels: Task 2, completed

#187 Text file added by Pallav
  Open Source/Git1/Pallav-Kumar-Patra.txt.txt
  Open Source/Git2/Pallav-Kumar-Patra.gif
Labels: Task 2, completed

#186 Task 2
  Open Source/Git2/Sneha.jpeg.jpeg
Labels: Task 2, completed

#185 Task 2 completed
  Open Source/Git2/asmi-jena.jpeg
Labels: Task 2, completed

#184 Task 2 completed
  Open Source/Git2/Meenakshi143.jpeg
Labels: Task 2, completed

#183 Task-complete
  Open Source/Git1/jyotiranjan-kunda.txt
  Open Source/Git2/jyotiranjan-kunda.jpg
Labels: Task 2, completed

#182 task 2
  Open Source/Git2/shraddha-suman-dash.jpeg.png
Labels: Task 2, completed

#181 Enigma Induction- Task1
  Open Source/Git1/Manas-Kumar-Panda.txt.txt
  Open Source/Git2/Manas-Kumar-Panda.jfif
Labels: Task 2, completed

#180 TASK 2
  Open Source/Git2/kareena-sahoo.jpg
Labels: Task 2, completed

#179 Image Added Task 2
  Open Source/Git2/Deepika-Kar.jpg
Labels: Task 2, completed

#178 Task 2 Completed
  Open Source/Git2/Chandan-Kumar-Dash.jpg
Labels: Task 2, completed

#177 Task -1 Completed
  Open Source/Git1/DEEPAMJYOTI.txt
Labels: Task 1, completed

#176 Task2 assignment "-"
  Open Source/Git2/kitty.png
Labels: Task 2, completed

#175 Task2 completed
  Open Source/Git1/sanskruti-raju.txt
  Open Source/Git2/sanskruti-raju.jpeg
Labels: Task 2, completed

#174 task 1
  Open Source/Git1/sidharth-kumar-sahu.txt
  Open Source/Git2/sidharth-kumar-sahu.jpeg
Labels: Task 2, completed

#173 Task-2 Completed
  Open Source/Git1/swaraj-kumar-singh.txt
  Open Source/Git2/swaraj-kumar-singh.jpg
Labels: Task 2, completed

#171 task 2 completed
  Open Source/Git2/Sourav-Kumar-Panda.jpeg.jpg
Labels: Task 2, completed

#170 Task-2 Assignment
  Open Source/Git2/Lalit_Kumar.jpg
Labels: Task 2, completed

#169 Add files via upload
  Open Source/Git1/pratik-naik.txt
  Open Source/Git2/Pratik-naik.jfif
Labels: Task 2, completed

#168 task 2 completed
  Open Source/Git2/Debesh_Mohapatra.jfif
Labels: Task 2, completed

#167 Task 2 complete
  Open Source/Git2/Biswajeet_Dehuri.png
Labels: Task 2, completed

#165 Task_2 Completed
  Open Source/Git2/pet_image.jpg
Labels: Task 2, completed

#164 Task 2 by ansuman mishra
  Open Source/Git2/ansuman-mishra.jpeg.jpeg
Labels: Task 2, completed

#163 task 2 completed
  Open Source/Git2/Sandeepan-Mohanty.jpg
Labels: Task 2, completed

#162 Add Task2 assignment
  Open Source/Git2/prasiddhi-sahu.jfif
Labels: Task 2, completed

#161 TASK 2
  Open Source/Git2/Ansuman Das.jpg
Labels: Task 2, completed

#159 task2
  Open Source/Git2/Aastha-Mohanty.jpg
Labels: Task 2, completed

#157 TASK_2
  Open Source/Git2/DOGE.png
Labels: Task 2, completed

#156 Task 1 Completed
  Open Source/Git1/Pritam_Patel.txt
  Open Source/Git2/Pritam_patel.jpeg
Labels: Task 2, completed

#155 task 2
  Open Source/Git2/Pratikshya-behera.jpg
Labels: Task 2, completed

#154 Task 2
  Open Source/Git2/Shubhrajyoti.png
Labels: Task 2, completed

#153 task-2-completed
  Open Source/Git2/Avinash-Kumar.png
Labels: Task 2, completed

#152 task 2
  Open Source/Git2/WhatsApp Image 2021-04-28 at 19.56.10.jpeg
Labels: Task 2, completed

#151 Merge pull request #1 from EnigmaVSSUT/main
  Open Source/Git2/Sthitaprajna-Biswal.jpeg
Labels: Task 2, completed

#149 image file added after repository updation
  Open Source/Git2/biswajit.jpeg
Labels: Task 2, completed

#146 task 2 completed
  Open Source/Git2/sibasundar_behera.jfif
Labels: Task 2, completed

#143 Rudramadhaba-mishra.jpg
  Open Source/Git2/Rudramadhaba-mishra.jpg
Labels: Task 2, completed

#142 Task 2 completed
  Open Source/Git2/Ruchira-Priyadarshani.jpg
Labels: Task 2, completed

#141 task 2
  Open Source/Git2/prachi-suman.jfif
Labels: Task 2, completed

#138 task-2
  Open Source/Git2/ChandanKumarHaboda.png
Labels: Task 2, completed

#137 Task2 completed
  Open Source/Git2/Ishita-Satpathy.jpg
Labels: Task 2, completed

#135 TASK 2 COMPLETED
  Open Source/Git2/Snehal-Senapati.jpg
Labels: Task 2, completed

#120 Task 2
  Open Source/Git2/tapu.jfif
Labels: Task 2, completed

#119 Task2
  Open Source/Git2/Pratham-Mishra.jpg
Labels: Task 2, completed

#118 Task 2 Assignment
  Open Source/Git2/Nikhil-Kumar-Sahu.jfif
Labels: Task 2, completed

#127 task2 completed
  Open Source/Git2/Dhairya-Joshi.jpg
Labels: Task 2, completed

#126 task 2
  Open Source/Git2/Riturani mohapatra.jpeg
Labels: Task 2, completed

#121 Task2 completed
  Open Source/Git2/md-adnaan-ansari.jpeg
Labels: Task 2, completed

#129 #Task 2 Completed
  Open Source/Git2/Harsh-Ranjan.JPG
Labels: Task 2, completed

#128 task 2
  Open Source/Git2/swagatika.jpeg
Labels: Task 2, completed

#134 Task 2 completed
  Open Source/Git2/Swadesh-Panda.jpg
Labels: Task 2, completed

#132 meenakshi-murmu.txt
  Open Source/Git1/meenakshi-murmu.txt
Labels: Task 1, completed

#131 Task 2
  Open Source/Git2/Ravindra-Nag.jpg
Labels: Task 2, completed

#130 Task 1 completed
  Open Source/Git1/Pooja.txt
  Open Source/Git2/Pooja.jpg
Labels: Task 2, completed

#124 Task 2
  Open Source/Git2/Ratan_Kumar_Tripathy.jpeg
Labels: Task 2, completed

#123 Task 1
  Open Source/Git1/Aashwasti-Pandia.txt
  Open Source/Git2/Aashwasti-Pandia.jpeg
Labels: Task 2, completed

#122 Task1
  Open Source/Git1/Dishant_Das.txt
  Open Source/Git2/Dishant_Das.jpg
Labels: Task 1, completed

#243 Task - 2 Completed
  Open Source/Git2/DEEPAMJYOTI.jpeg
Labels: Late, Task 2, completed

#250 Create Jyotirmayee-Nanda.jpg
  Open Source/Git2/Jyotirmayee-Nanda.jpg
Labels: Late, Task 2, completed

#207 task 1 completed
  Open Source/Git1/prativarath.txt
  Open Source/Git2/prativa.jpg
Labels: Late, Task 2, completed

#255 Prasoon Nayak/Induction 2021
  Open Source/Git1/Prasoon Nayak.txt
  Open Source/Git2/Prasoon Nayak.jpg
Labels: Late, Task 2, completed

#268 task 3 completed
  Web Development/Task-1/Task submission/shraddha-suman/Screenshot (27).png
  Web Development/Task-1/Task submission/shraddha-suman/index.html
  Web Development/Task-1/Task submission/shraddha-suman/shraddha.txt
Labels: Task 1, Web Dev, completed

#333 Web Dev Task 1 & 2
  Web Development/Task-1/Task submission/Ravindra-Nag/.vs/ProjectSettings.json
  Web Development/Task-1/Task submission/Ravindra-Nag/.vs/VSWorkspaceState.json
  Web Development/Task-1/Task submission/Ravindra-Nag/.vs/aboutme/config/applicationhost.config
  Web Development/Task-1/Task submission/Ravindra-Nag/.vs/aboutme/v16/.suo
  Web Development/Task-1/Task submission/Ravindra-Nag/.vs/slnx.sqlite
  Web Development/Task-1/Task submission/Ravindra-Nag/css/style.css
  Web Development/Task-1/Task submission/Ravindra-Nag/index.html
  Web Development/Task-1/Task submission/Ravindra-Nag/link.txt
  Web Development/Task-1/Task submission/Ravindra-Nag/photos/pfp.webp
  Web Development/Task-1/Task submission/Ravindra-Nag/webdev_task_1.png
  Web Development/Task-2/Task submission/Ravindra-Nag/.vs/ProjectSettings.json
  Web Development/Task-2/Task submission/Ravindra-Nag/.vs/VSWorkspaceState.json
  Web Development/Task-2/Task submission/Ravindra-Nag/.vs/aboutme/config/applicationhost.config
  Web Development/Task-2/Task submission/Ravindra-Nag/.vs/aboutme/v16/.suo
  Web Development/Task-2/Task submission/Ravindra-Nag/.vs/slnx.sqlite
  Web Development/Task-2/Task submission/Ravindra-Nag/css/style.css
  Web Development/Task-2/Task submission/Ravindra-Nag/index.html
  Web Development/Task-2/Task submission/Ravindra-Nag/js/script.js
  Web Development/Task-2/Task submission/Ravindra-Nag/link.txt
  Web Development/Task-2/Task submission/Ravindra-Nag/photos/pfp.webp
  Web Development/Task-2/Task submission/Ravindra-Nag/web-dev-task-2-dark.png
  Web Development/Task-2/Task submission/Ravindra-Nag/web-dev-task-2-light.png
Labels: Task 2, Web Dev, completed

#331 task 1 and task 2 completed
  Web Development/Task-1/Task submission/pramit-singh/Pramit.png
  Web Development/Task-1/Task submission/pramit-singh/Screenshot.jpg
  Web Development/Task-1/Task submission/pramit-singh/index.html
  Web Development/Task-1/Task submission/pramit-singh/pramit-singh.txt
  Web Development/Task-1/Task submission/pramit-singh/style.css
  Web Development/Task-2/Task submission/pramit-singh/Pramit.png
  Web Development/Task-2/Task submission/pramit-singh/darkwebpage.png
  Web Development/Task-2/Task submission/pramit-singh/index.html
  Web Development/Task-2/Task submission/pramit-singh/lightwebpage.png
  Web Development/Task-2/Task submission/pramit-singh/pramit-singh.txt
  Web Development/Task-2/Task submission/pramit-singh/style.css
Labels: Task 2, Web Dev, completed

#330 Task 1 and Task 2 done by rudramadhaba mishra
  Web Development/Task-1/Task submission/Rudramadhab-mishra/index.html
  Web Development/Task-1/Task submission/Rudramadhab-mishra/link.txt
  Web Development/Task-1/Task submission/Rudramadhab-mishra/new.css
  Web Development/Task-1/Task submission/Rudramadhab-mishra/pic/RM.jpg
  Web Development/Task-1/Task submission/Rudramadhab-mishra/pic/photu2.jpg
  Web Development/Task-2/Task submission/Rudramadhaba-mishra/dark mode.png
  Web Development/Task-2/Task submission/Rudramadhaba-mishra/index.html
  Web Development/Task-2/Task submission/Rudramadhaba-mishra/light mode.png
  Web Development/Task-2/Task submission/Rudramadhaba-mishra/link2.txt
  Web Development/Task-2/Task submission/Rudramadhaba-mishra/new.css
  Web Development/Task-2/Task submission/Rudramadhaba-mishra/pic/RM.jpg
  Web Development/Task-2/Task submission/Rudramadhaba-mishra/pic/photu2.jpg
Labels: Task 2, Web Dev, completed

#329 Task 1 and 2
  Web Development/Task-1/Task submission/Sthitaprajna Biswal/Sthitaprajna.txt
  Web Development/Task-1/Task submission/Sthitaprajna Biswal/coding.jpg
  Web Development/Task-1/Task submission/Sthitaprajna Biswal/index.html
  Web Development/Task-1/Task submission/Sthitaprajna Biswal/style.css
  Web Development/Task-2/Task submission/Sthitaprajna Biswal/Sthitaprajna.txt.txt
  Web Development/Task-2/Task submission/Sthitaprajna Biswal/dark.jpg
  Web Development/Task-2/Task submission/Sthitaprajna Biswal/image.jpg
  Web Development/Task-2/Task submission/Sthitaprajna Biswal/index.html
  Web Development/Task-2/Task submission/Sthitaprajna Biswal/light.jpg
  Web Development/Task-2/Task submission/Sthitaprajna Biswal/script.js
  Web Development/Task-2/Task submission/Sthitaprajna Biswal/style.css
Labels: Task 2, Web Dev, completed

#327 task3
  Web Development/Task-1/Task submission/sidharth-kumar/Screenshot (2).png
  Web Development/Task-1/Task submission/sidharth-kumar/index.html
  Web Development/Task-1/Task submission/sidharth-kumar/link.txt
Labels: Task 1, Web Dev, completed

#324 web dev task 1 and task 2
  Web Development/Task-1/Task submission/Astha Niharika/dwld1.png
  Web Development/Task-1/Task submission/Astha Niharika/dwld2.jpg
  Web Development/Task-1/Task submission/Astha Niharika/dwld3.jpg
  Web Development/Task-1/Task submission/Astha Niharika/index.html
  Web Development/Task-1/Task submission/Astha Niharika/screenshot (1).png
  Web Development/Task-1/Task submission/Astha Niharika/screenshot (2).png
  Web Development/Task-1/Task submission/Astha Niharika/screenshot (3).png
  Web Development/Task-1/Task submission/Astha Niharika/style.css
  Web Development/Task-1/Task submission/Astha Niharika/url.txt
  Web Development/Task-2/Task submission/Astha Niharika/dwld1.png
  Web Development/Task-2/Task submission/Astha Niharika/dwld2.jpg
  Web Development/Task-2/Task submission/Astha Niharika/dwld3.jpg
  Web Development/Task-2/Task submission/Astha Niharika/index.html
  Web Development/Task-2/Task submission/Astha Niharika/screenshot (1).png
  Web Development/Task-2/Task submission/Astha Niharika/screenshot (2).png
  Web Development/Task-2/Task submission/Astha Niharika/screenshot (3).png
  Web Development/Task-2/Task submission/Astha Niharika/screenshot (4).png
  Web Development/Task-2/Task submission/Astha Niharika/script.js
  Web Development/Task-2/Task submission/Astha Niharika/style.css
  Web Development/Task-2/Task submission/Astha Niharika/url.txt
Labels: Task 2, Web Dev, completed

#323 Web Task1 and Task2 Completed
  Web Development/Task-1/Task submission/Anweshita Mohanty/anweshita.jpg
  Web Development/Task-1/Task submission/Anweshita Mohanty/index.html
  Web Development/Task-1/Task submission/Anweshita Mohanty/link.txt
  Web Development/Task-1/Task submission/Anweshita Mohanty/style.css
  Web Development/Task-1/Task submission/Anweshita Mohanty/webpage ss.png
  Web Development/Task-2/Task submission/TASK 2 Anweshita/anweshita.jpg
  Web Development/Task-2/Task submission/TASK 2 Anweshita/dark sample.png
  Web Development/Task-2/Task submission/TASK 2 Anweshita/index.html
  Web Development/Task-2/Task submission/TASK 2 Anweshita/light sample.png
  Web Development/Task-2/Task submission/TASK 2 Anweshita/link.txt
  Web Development/Task-2/Task submission/TASK 2 Anweshita/style.css
Labels: Task 2, Web Dev, completed

#319 task 2
  Web Development/Task-2/Task submission/shraddha/Screenshot (30).png
  Web Development/Task-2/Task submission/shraddha/dark_Sample.jpeg
  Web Development/Task-2/Task submission/shraddha/index.html
  Web Development/Task-2/Task submission/shraddha/light_Sample.jpeg
Labels: Task 2, Web Dev, completed

#317 both tasks done
  Web Development/Task-1/Task submission/biswajit/images/about_me.png
  Web Development/Task-1/Task submission/biswajit/images/games.jfif
  Web Development/Task-1/Task submission/biswajit/images/interests.jpeg
  Web Development/Task-1/Task submission/biswajit/images/music.jfif
  Web Development/Task-1/Task submission/biswajit/images/skills.jpg
  Web Development/Task-1/Task submission/biswajit/index.html
  Web Development/Task-1/Task submission/biswajit/task_screenshot.png
  Web Development/Task-1/Task submission/biswajit/url.txt
  Web Development/Task-2/Task submission/biswajit_nayak/images/about_me.png
  Web Development/Task-2/Task submission/biswajit_nayak/images/games.jfif
  Web Development/Task-2/Task submission/biswajit_nayak/images/interests.jpeg
  Web Development/Task-2/Task submission/biswajit_nayak/images/music.jfif
  Web Development/Task-2/Task submission/biswajit_nayak/images/skills.jpg
  Web Development/Task-2/Task submission/biswajit_nayak/index.html
  Web Development/Task-2/Task submission/biswajit_nayak/url.txt
Labels: Task 2, Web Dev, completed

#316 Task1 and Task2
  Web Development/Task-1/Task submission/prasiddhi-sahu/New Text Document.txt
  Web Development/Task-1/Task submission/prasiddhi-sahu/README.md
  Web Development/Task-1/Task submission/prasiddhi-sahu/index.html
  Web Development/Task-1/Task submission/prasiddhi-sahu/ss.PNG
  Web Development/Task-1/Task submission/prasiddhi-sahu/style.css
  Web Development/Task-2/Task submission/prasiddhi-sahu/New Text Document.txt
  Web Development/Task-2/Task submission/prasiddhi-sahu/README.md
  Web Development/Task-2/Task submission/prasiddhi-sahu/index.html
  Web Development/Task-2/Task submission/prasiddhi-sahu/style1.css
Labels: Task 2, Web Dev, completed

#314 WEV_DEV TASK_1 & TASK_2
  Web Development/Task-1/Task submission/Somanath_Singh/DOGE.png
  Web Development/Task-1/Task submission/Somanath_Singh/HOBBY1.jpg
  Web Development/Task-1/Task submission/Somanath_Singh/PROFILE.jpg
  Web Development/Task-1/Task submission/Somanath_Singh/SKILL1.jpg
  Web Development/Task-1/Task submission/Somanath_Singh/SS.png
  Web Development/Task-1/Task submission/Somanath_Singh/index.html
  Web Development/Task-1/Task submission/Somanath_Singh/link.txt
  Web Development/Task-2/Task submission/Somanath Singh/DOGE.png
  Web Development/Task-2/Task submission/Somanath Singh/HOBBY1.jpg
  Web Development/Task-2/Task submission/Somanath Singh/PROFILE.jpg
  Web Development/Task-2/Task submission/Somanath Singh/SKILL1.jpg
  Web Development/Task-2/Task submission/Somanath Singh/SS.png
  Web Development/Task-2/Task submission/Somanath Singh/SS2.png
  Web Development/Task-2/Task submission/Somanath Singh/index.html
  Web Development/Task-2/Task submission/Somanath Singh/link.txt
Labels: Task 2, Web Dev, completed

#313 Task 3
  Web Development/Task-1/Task submission/Aditya-Singh/IMG_20201119_214923_294.jpg
  Web Development/Task-1/Task submission/Aditya-Singh/Screenshot (3).png
  Web Development/Task-1/Task submission/Aditya-Singh/cricket.jpg
  Web Development/Task-1/Task submission/Aditya-Singh/index.html
  Web Development/Task-1/Task submission/Aditya-Singh/logo.jpg
  Web Development/Task-1/Task submission/Aditya-Singh/style.css
  Web Development/Task-1/Task submission/Aditya-Singh/url.txt
  Web Development/Task-2/Task submission/aditya-singh/IMG_20201119_214923_294.jpg
  Web Development/Task-2/Task submission/aditya-singh/Screenshot (7).png
  Web Development/Task-2/Task submission/aditya-singh/cricket.jpg
  Web Development/Task-2/Task submission/aditya-singh/index.html
  Web Development/Task-2/Task submission/aditya-singh/logo.jpg
  Web Development/Task-2/Task submission/aditya-singh/style.css
  Web Development/Task-2/Task submission/aditya-singh/url.txt
Labels: Late, Task 2, Web Dev, completed

#308 Web dev Task1 and Task2
  Web Development/Task-1/Task submission/Abhaya Padhi/im2.jpg
  Web Development/Task-1/Task submission/Abhaya Padhi/im3.jpg
  Web Development/Task-1/Task submission/Abhaya Padhi/image.jpg
  Web Development/Task-1/Task submission/Abhaya Padhi/index.html
  Web Development/Task-1/Task submission/Abhaya Padhi/style.css
  Web Development/Task-1/Task submission/Abhaya Padhi/url.txt.txt
  Web Development/Task-1/Task submission/Abhaya Padhi/website.PNG
  Web Development/Task-2/Task submission/Abhaya Padhi/im2.jpg
  Web Development/Task-2/Task submission/Abhaya Padhi/im3.jpg
  Web Development/Task-2/Task submission/Abhaya Padhi/image.jpg
  Web Development/Task-2/Task submission/Abhaya Padhi/index.html
  Web Development/Task-2/Task submission/Abhaya Padhi/index.js
  Web Development/Task-2/Task submission/Abhaya Padhi/style.css
  Web Development/Task-2/Task submission/Abhaya Padhi/url.txt.txt
Labels: Task 2, Web Dev, completed

#307 task 1 and 2
  Web Development/Task-1/Task submission/sushobhan biswal/CSS/style.css
  Web Development/Task-1/Task submission/sushobhan biswal/WEBpage.png
  Web Development/Task-1/Task submission/sushobhan biswal/alter.js
  Web Development/Task-1/Task submission/sushobhan biswal/images/skill.jpg
  Web Development/Task-1/Task submission/sushobhan biswal/images/sushobhan biswal.jpeg
  Web Development/Task-1/Task submission/sushobhan biswal/images/wallhaven-3zl796_1920x1080.png
  Web Development/Task-1/Task submission/sushobhan biswal/images/wallhaven-eymzjk_1920x1080.png
  Web Development/Task-1/Task submission/sushobhan biswal/images/wallhaven-g7jg63_1920x1080.png
  Web Development/Task-1/Task submission/sushobhan biswal/index.html
  Web Development/Task-1/Task submission/sushobhan biswal/url.txt
  Web Development/Task-2/Task submission/sushobhan biswal/CSS/style.css
  Web Development/Task-2/Task submission/sushobhan biswal/WEBpage.png
  Web Development/Task-2/Task submission/sushobhan biswal/WEBpagedark.png
  Web Development/Task-2/Task submission/sushobhan biswal/alter.js
  Web Development/Task-2/Task submission/sushobhan biswal/images/skill.jpg
  Web Development/Task-2/Task submission/sushobhan biswal/images/sushobhan biswal.jpeg
  Web Development/Task-2/Task submission/sushobhan biswal/images/wallhaven-3zl796_1920x1080.png
  Web Development/Task-2/Task submission/sushobhan biswal/images/wallhaven-eymzjk_1920x1080.png
  Web Development/Task-2/Task submission/sushobhan biswal/images/wallhaven-g7jg63_1920x1080.png
  Web Development/Task-2/Task submission/sushobhan biswal/index.html
  Web Development/Task-2/Task submission/sushobhan biswal/url.txt
Labels: Task 2, Web Dev, completed

#301 task 3 submitted
  Web Development/Task-1/Task submission/sourav kumar panda/coding.jpg
  Web Development/Task-1/Task submission/sourav kumar panda/index.html
  Web Development/Task-1/Task submission/sourav kumar panda/my img.jpeg
  Web Development/Task-1/Task submission/sourav kumar panda/sourav-kumar-panda.txt
  Web Development/Task-1/Task submission/sourav kumar panda/style.css
  Web Development/Task-1/Task submission/sourav kumar panda/web dev.jpg
  Web Development/Task-2/Task submission/Sourav Kumar Panda/coding.jpg
  Web Development/Task-2/Task submission/Sourav Kumar Panda/index.html
  Web Development/Task-2/Task submission/Sourav Kumar Panda/my img.jpeg
  Web Development/Task-2/Task submission/Sourav Kumar Panda/sourav-kumar-panda.txt
  Web Development/Task-2/Task submission/Sourav Kumar Panda/style.css
  Web Development/Task-2/Task submission/Sourav Kumar Panda/web dev.jpg
Labels: Task 2, Web Dev, completed

#300 task3
  Web Development/Task-1/Task submission/ansuman-mishra/ai.jpg
  Web Development/Task-1/Task submission/ansuman-mishra/bg.jpeg
  Web Development/Task-1/Task submission/ansuman-mishra/cc.jpg
  Web Development/Task-1/Task submission/ansuman-mishra/index.html.html
  Web Development/Task-1/Task submission/ansuman-mishra/me.jpg
  Web Development/Task-1/Task submission/ansuman-mishra/ps.jpg
  Web Development/Task-1/Task submission/ansuman-mishra/style.css.css
  Web Development/Task-1/Task submission/ansuman-mishra/url.txt.txt
  Web Development/Task-1/Task submission/ansuman-mishra/web ss.png
  Web Development/Task-2/Task submission/ansuman-mishra/ai.jpg
  Web Development/Task-2/Task submission/ansuman-mishra/bg.jpeg
  Web Development/Task-2/Task submission/ansuman-mishra/cc.jpg
  Web Development/Task-2/Task submission/ansuman-mishra/index.html.html
  Web Development/Task-2/Task submission/ansuman-mishra/me.jpg
  Web Development/Task-2/Task submission/ansuman-mishra/ps.jpg
  Web Development/Task-2/Task submission/ansuman-mishra/sbg.jpg
  Web Development/Task-2/Task submission/ansuman-mishra/style.css.css
  Web Development/Task-2/Task submission/ansuman-mishra/theme.js.js
  Web Development/Task-2/Task submission/ansuman-mishra/url.txt.txt
Labels: Task 2, Web Dev, completed

#299 Web Development Task 1 & Task 2
  Web Development/Task-1/Task submission/Adarsh Goswami/Website Link.txt
  Web Development/Task-1/Task submission/Adarsh Goswami/images/Facebook-logo.png
  Web Development/Task-1/Task submission/Adarsh Goswami/images/Screenshot (330).png
  Web Development/Task-1/Task submission/Adarsh Goswami/images/Screenshot (331).png
  Web Development/Task-1/Task submission/Adarsh Goswami/images/Screenshot (332).png
  Web Development/Task-1/Task submission/Adarsh Goswami/images/c++.png
  Web Development/Task-1/Task submission/Adarsh Goswami/images/cooking.jpg
  Web Development/Task-1/Task submission/Adarsh Goswami/images/instagram.png
  Web Development/Task-1/Task submission/Adarsh Goswami/images/linkedin.png
  Web Development/Task-1/Task submission/Adarsh Goswami/images/my interests.jpg
  Web Development/Task-1/Task submission/Adarsh Goswami/images/my photo.png
  Web Development/Task-1/Task submission/Adarsh Goswami/images/ps.png
  Web Development/Task-1/Task submission/Adarsh Goswami/images/twitter.png
  Web Development/Task-1/Task submission/Adarsh Goswami/index.html
  Web Development/Task-1/Task submission/Adarsh Goswami/scripts.js
  Web Development/Task-1/Task submission/Adarsh Goswami/styles.css
  Web Development/Task-2/Task submission/Adarsh Goswami/Website Link.txt
  Web Development/Task-2/Task submission/Adarsh Goswami/images/Facebook-logo.png
  Web Development/Task-2/Task submission/Adarsh Goswami/images/Screenshot (330).png
  Web Development/Task-2/Task submission/Adarsh Goswami/images/Screenshot (331).png
  Web Development/Task-2/Task submission/Adarsh Goswami/images/Screenshot (332).png
  Web Development/Task-2/Task submission/Adarsh Goswami/images/c++.png
  Web Development/Task-2/Task submission/Adarsh Goswami/images/cooking.jpg
  Web Development/Task-2/Task submission/Adarsh Goswami/images/instagram.png
  Web Development/Task-2/Task submission/Adarsh Goswami/images/linkedin.png
  Web Development/Task-2/Task submission/Adarsh Goswami/images/my interests.jpg
  Web Development/Task-2/Task submission/Adarsh Goswami/images/my photo.png
  Web Development/Task-2/Task submission/Adarsh Goswami/images/ps.png
  Web Development/Task-2/Task submission/Adarsh Goswami/images/twitter.png
  Web Development/Task-2/Task submission/Adarsh Goswami/index.html
  Web Development/Task-2/Task submission/Adarsh Goswami/scripts.js
  Web Development/Task-2/Task submission/Adarsh Goswami/styles.css
Labels: Task 2, Web Dev, completed

#297 Web Page Task1 and Task2
  Web Development/Task-1/Task submission/swaraj-kumar-singh/PicsArt_05-13-11.24.21.jpg
  Web Development/Task-1/Task submission/swaraj-kumar-singh/Skill.jpg
  Web Development/Task-1/Task submission/swaraj-kumar-singh/Skimg.jpg
  Web Development/Task-1/Task submission/swaraj-kumar-singh/background.jpg
  Web Development/Task-1/Task submission/swaraj-kumar-singh/index.html
  Web Development/Task-1/Task submission/swaraj-kumar-singh/page-ss/Opera Snapshot_2021-05-14_164714_swaraj79.github.io.png
  Web Development/Task-1/Task submission/swaraj-kumar-singh/page-url.txt
  Web Development/Task-1/Task submission/swaraj-kumar-singh/style.css
  Web Development/Task-2/Task submission/swaraj-kumar-singh/Page SS/Snapshot_swarajsingh_dark-mode.png
  Web Development/Task-2/Task submission/swaraj-kumar-singh/Page SS/Snapshot_swarajsingh_light-mode.png
  Web Development/Task-2/Task submission/swaraj-kumar-singh/PicsArt_05-13-11.24.21.jpg
  Web Development/Task-2/Task submission/swaraj-kumar-singh/Skill.jpg
  Web Development/Task-2/Task submission/swaraj-kumar-singh/Skimg.jpg
  Web Development/Task-2/Task submission/swaraj-kumar-singh/backgroung.jpg
  Web Development/Task-2/Task submission/swaraj-kumar-singh/darkbkgd.jpg
  Web Development/Task-2/Task submission/swaraj-kumar-singh/index.html
  Web Development/Task-2/Task submission/swaraj-kumar-singh/index.js
  Web Development/Task-2/Task submission/swaraj-kumar-singh/page-url.txt
  Web Development/Task-2/Task submission/swaraj-kumar-singh/style.css
Labels: Late, Task 2, Web Dev, completed

#294 WebDev Task1 Completed
  Web Development/Task-1/Task submission/Chandan-Kumar-Dash/As1CSS.css
  Web Development/Task-1/Task submission/Chandan-Kumar-Dash/MyWebpageScreenshot.PNG
  Web Development/Task-1/Task submission/Chandan-Kumar-Dash/as1.jpg
  Web Development/Task-1/Task submission/Chandan-Kumar-Dash/hobby.jpg
  Web Development/Task-1/Task submission/Chandan-Kumar-Dash/hosted github Link.txt
  Web Development/Task-1/Task submission/Chandan-Kumar-Dash/index.html
  Web Development/Task-1/Task submission/Chandan-Kumar-Dash/inte.jpeg
  Web Development/Task-1/Task submission/Chandan-Kumar-Dash/me.jpg
  Web Development/Task-1/Task submission/Chandan-Kumar-Dash/skill.jpg
  Web Development/Task-2/Task submission/Chandan-Kumar-Dash/As1CSS.css
  Web Development/Task-2/Task submission/Chandan-Kumar-Dash/MyWebpageScreenshot.PNG
  Web Development/Task-2/Task submission/Chandan-Kumar-Dash/as1.jpg
  Web Development/Task-2/Task submission/Chandan-Kumar-Dash/hobby.jpg
  Web Development/Task-2/Task submission/Chandan-Kumar-Dash/hosted github Link.txt
  Web Development/Task-2/Task submission/Chandan-Kumar-Dash/index.html
  Web Development/Task-2/Task submission/Chandan-Kumar-Dash/inte.jpeg
  Web Development/Task-2/Task submission/Chandan-Kumar-Dash/me.jpg
  Web Development/Task-2/Task submission/Chandan-Kumar-Dash/skill.jpg
Labels: Task 2, Web Dev, completed

#293 Task 1 Web Dev
  Web Development/Task-1/Task submission/README.md
  Web Development/Task-1/Task submission/Ratan_Kumar_Tripathy/Ratan_Kumar_Tripathy.jpeg
  Web Development/Task-1/Task submission/Ratan_Kumar_Tripathy/Task1pic.png
  Web Development/Task-1/Task submission/Ratan_Kumar_Tripathy/cool.jpg
  Web Development/Task-1/Task submission/Ratan_Kumar_Tripathy/index.html
  Web Development/Task-1/Task submission/Ratan_Kumar_Tripathy/style.css
  Web Development/Task-1/Task submission/Ratan_Kumar_Tripathy/sun.jpg
  Web Development/Task-1/Task submission/Ratan_Kumar_Tripathy/webpage link.txt
  Web Development/Task-2/Task submission/Ratan Kumar Tripathy/Ratan_Kumar_Tripathy.jpeg
  Web Development/Task-2/Task submission/Ratan Kumar Tripathy/cool.jpg
  Web Development/Task-2/Task submission/Ratan Kumar Tripathy/index.html
  Web Development/Task-2/Task submission/Ratan Kumar Tripathy/style.css
  Web Development/Task-2/Task submission/Ratan Kumar Tripathy/sun.jpg
  Web Development/Task-2/Task submission/Ratan Kumar Tripathy/task2 link.txt
  Web Development/Task-2/Task submission/Ratan Kumar Tripathy/theme.js
Labels: Task 2, Web Dev, completed

#292 Web-Dev-task1
  Web Development/Task-1/Task submission/gayatri choudhary/URL.txt
  Web Development/Task-1/Task submission/gayatri choudhary/cover.png
  Web Development/Task-1/Task submission/gayatri choudhary/index.html
  Web Development/Task-1/Task submission/gayatri choudhary/me.jpg
  Web Development/Task-1/Task submission/gayatri choudhary/screenshot.png
  Web Development/Task-1/Task submission/gayatri choudhary/style.css
  Web Development/Task-2/Task submission/gayatri choudhary/URL.txt
  Web Development/Task-2/Task submission/gayatri choudhary/after.png
  Web Development/Task-2/Task submission/gayatri choudhary/before.png
  Web Development/Task-2/Task submission/gayatri choudhary/cover.png
  Web Development/Task-2/Task submission/gayatri choudhary/index.html
  Web Development/Task-2/Task submission/gayatri choudhary/me.jpg
  Web Development/Task-2/Task submission/gayatri choudhary/script.js
  Web Development/Task-2/Task submission/gayatri choudhary/style.css
Labels: Task 2, Web Dev, completed

#290 task 3
  Web Development/Task-1/Task submission/Hemadri_Tanaya/CSS/style.css
  Web Development/Task-1/Task submission/Hemadri_Tanaya/a.png
  Web Development/Task-1/Task submission/Hemadri_Tanaya/index.html
  Web Development/Task-1/Task submission/Hemadri_Tanaya/my logo.jpg
  Web Development/Task-1/Task submission/Hemadri_Tanaya/themedark.png
  Web Development/Task-1/Task submission/Hemadri_Tanaya/url.txt
  Web Development/Task-1/Task submission/Hemadri_Tanaya/webcap.png
  Web Development/Task-2/Task submission/hema/CSS/style.css
  Web Development/Task-2/Task submission/hema/a.png
  Web Development/Task-2/Task submission/hema/index.html
  Web Development/Task-2/Task submission/hema/my logo.jpg
  Web Development/Task-2/Task submission/hema/themedark.png
  Web Development/Task-2/Task submission/hema/url.txt
Labels: Task 1, Task 2, Web Dev, completed

#286 web task-1 completed
  Web Development/Task-1/Task submission/tanusriya_mahawar/girl.jpg
  Web Development/Task-1/Task submission/tanusriya_mahawar/index.html
  Web Development/Task-1/Task submission/tanusriya_mahawar/index.txt
  Web Development/Task-1/Task submission/tanusriya_mahawar/link.txt
  Web Development/Task-1/Task submission/tanusriya_mahawar/web-page-ss.png
  Web Development/Task-2/Task submission/tanu.m/dark_sample.jpg
  Web Development/Task-2/Task submission/tanu.m/girl.jpg
  Web Development/Task-2/Task submission/tanu.m/index22.html
  Web Development/Task-2/Task submission/tanu.m/index22.txt
  Web Development/Task-2/Task submission/tanu.m/light_sample.jpg
  Web Development/Task-2/Task submission/tanu.m/link.txt
Labels: Task 2, Web Dev, completed

#285 task one
  Web Development/Task-1/Task submission/yash/index.html
  Web Development/Task-1/Task submission/yash/interests.jpg
  Web Development/Task-1/Task submission/yash/skills.png
  Web Development/Task-1/Task submission/yash/task1 screencapture.png
  Web Development/Task-1/Task submission/yash/url.txt
  Web Development/Task-1/Task submission/yash/yash.jpg
  Web Development/Task-2/Task submission/yashjain/index.html
  Web Development/Task-2/Task submission/yashjain/interests.jpg
  Web Development/Task-2/Task submission/yashjain/skills.png
  Web Development/Task-2/Task submission/yashjain/task2 screencapture.png
  Web Development/Task-2/Task submission/yashjain/task2 url.txt
  Web Development/Task-2/Task submission/yashjain/yash.jpg
Labels: Task 2, Web Dev, completed

#284 task1
  Web Development/Task-1/Task submission/prachi-suman/1.png
  Web Development/Task-1/Task submission/prachi-suman/2.png
  Web Development/Task-1/Task submission/prachi-suman/dark 1.png
  Web Development/Task-1/Task submission/prachi-suman/dark 2.png
  Web Development/Task-1/Task submission/prachi-suman/index.html
  Web Development/Task-1/Task submission/prachi-suman/prachi.css
  Web Development/Task-1/Task submission/prachi-suman/simpson4.png
  Web Development/Task-1/Task submission/prachi-suman/url.txt
  Web Development/Task-2/Task submission/prachi-suman/1.png
  Web Development/Task-2/Task submission/prachi-suman/2.png
  Web Development/Task-2/Task submission/prachi-suman/dark 1.png
  Web Development/Task-2/Task submission/prachi-suman/dark 2.png
  Web Development/Task-2/Task submission/prachi-suman/index.html
  Web Development/Task-2/Task submission/prachi-suman/prachi.css
  Web Development/Task-2/Task submission/prachi-suman/simpson4.png
  Web Development/Task-2/Task submission/prachi-suman/url.txt
Labels: Task 2, Web Dev, completed

#283 web page completed
  Web Development/Task-1/Task submission/sandeepan/URL.txt
  Web Development/Task-1/Task submission/sandeepan/about me.png
  Web Development/Task-1/Task submission/sandeepan/gyu.jpg
  Web Development/Task-1/Task submission/sandeepan/hobbies.jpg
  Web Development/Task-1/Task submission/sandeepan/imgh.jpg
  Web Development/Task-1/Task submission/sandeepan/index.htm
  Web Development/Task-1/Task submission/sandeepan/my interest.jpg
  Web Development/Task-1/Task submission/sandeepan/mystyle.css
  Web Development/Task-1/Task submission/sandeepan/skills.png
  Web Development/Task-1/Task submission/sandeepan/webpage.png
Labels: Task 1, Web Dev, completed

#282 https://snehalsenapati23.github.io/ABOUT-ME/
  Web Development/Task-1/Task submission/snehal senapati/enigma (2).png
  Web Development/Task-1/Task submission/snehal senapati/enigma.css
  Web Development/Task-1/Task submission/snehal senapati/index.html
  Web Development/Task-1/Task submission/snehal senapati/om.jpg
  Web Development/Task-1/Task submission/snehal senapati/snehal senapati.txt
  Web Development/Task-2/Task submission/SNEHAL SENAPATI/WEB PAGE URL.txt
  Web Development/Task-2/Task submission/SNEHAL SENAPATI/after1 (2).png
  Web Development/Task-2/Task submission/SNEHAL SENAPATI/before (2).png
  Web Development/Task-2/Task submission/SNEHAL SENAPATI/enigma.css
  Web Development/Task-2/Task submission/SNEHAL SENAPATI/enigma.js
  Web Development/Task-2/Task submission/SNEHAL SENAPATI/index.html
  Web Development/Task-2/Task submission/SNEHAL SENAPATI/om.jpg
Labels: Task 2, Web Dev, completed

#281 task1 web
  Web Development/Task-1/Task submission/swagatika_panda/Computer-Coding-Laptop.jpg
  Web Development/Task-1/Task submission/swagatika_panda/acrylic.jpg
  Web Development/Task-1/Task submission/swagatika_panda/adress.txt.txt
  Web Development/Task-1/Task submission/swagatika_panda/blue.jpg
  Web Development/Task-1/Task submission/swagatika_panda/code1.png
  Web Development/Task-1/Task submission/swagatika_panda/code2.png
  Web Development/Task-1/Task submission/swagatika_panda/index.html
  Web Development/Task-1/Task submission/swagatika_panda/me.jpg
  Web Development/Task-1/Task submission/swagatika_panda/webpage.png
  Web Development/Task-2/Task submission/swagatika-panda/Computer-Coding-Laptop.jpg
  Web Development/Task-2/Task submission/swagatika-panda/acrylic.jpg
  Web Development/Task-2/Task submission/swagatika-panda/blue.jpg
  Web Development/Task-2/Task submission/swagatika-panda/index.html
  Web Development/Task-2/Task submission/swagatika-panda/me.jpg
  Web Development/Task-2/Task submission/swagatika-panda/newpage.txt
  Web Development/Task-2/Task submission/swagatika-panda/theme.js
Labels: Task 2, Web Dev, completed

#238 Task 2
  Open Source/Git2/Debabrata-Mohapatra.jfif
  Web Development/Task-1/Task submission/Debabrata-Mohapatra/Debabrata.txt
  Web Development/Task-1/Task submission/Debabrata-Mohapatra/Screenshot.png
  Web Development/Task-1/Task submission/Debabrata-Mohapatra/image.jpg
  Web Development/Task-1/Task submission/Debabrata-Mohapatra/index.html
  Web Development/Task-1/Task submission/Debabrata-Mohapatra/style.css
  Web Development/Task-2/Task submission/Debabrata-Mohapatra/after.png
  Web Development/Task-2/Task submission/Debabrata-Mohapatra/before.png
  Web Development/Task-2/Task submission/Debabrata-Mohapatra/image.jpg
  Web Development/Task-2/Task submission/Debabrata-Mohapatra/index.html
  Web Development/Task-2/Task submission/Debabrata-Mohapatra/script.js
  Web Development/Task-2/Task submission/Debabrata-Mohapatra/style.css
  Web Development/Task-2/Task submission/Debabrata-Mohapatra/url.txt
Labels: Git And Github, Late Git and github, Task 2, Web Dev, completed

#260 Task 3 completed
  Web Development/Task-1/Task submission/sibasundar behera/index.html
  Web Development/Task-1/Task submission/sibasundar behera/siba.txt.txt
  Web Development/Task-1/Task submission/sibasundar behera/siba_web_dev.png
  Web Development/Task-1/Task submission/sibasundar behera/style.css
  Web Development/Task-2/Task submission/sibasundar behera/index.html
  Web Development/Task-2/Task submission/sibasundar behera/siba.txt
Labels: Task 1, Task 2, Web Dev, completed

#263 Task-1 and Task-2 web development completed
  Web Development/Task-1/Task submission/Swayam Prakash Barik/Screenshot (2).png
  Web Development/Task-1/Task submission/Swayam Prakash Barik/coding.jpg
  Web Development/Task-1/Task submission/Swayam Prakash Barik/index.html
  Web Development/Task-1/Task submission/Swayam Prakash Barik/style.css
  Web Development/Task-1/Task submission/Swayam Prakash Barik/url.txt.txt
  Web Development/Task-2/Task submission/Swayam Prakash BARIK/Dark theme.png
  Web Development/Task-2/Task submission/Swayam Prakash BARIK/Light theme.png
  Web Development/Task-2/Task submission/Swayam Prakash BARIK/coding.jpg
  Web Development/Task-2/Task submission/Swayam Prakash BARIK/index.html
  Web Development/Task-2/Task submission/Swayam Prakash BARIK/style.css
  Web Development/Task-2/Task submission/Swayam Prakash BARIK/theme.js
  Web Development/Task-2/Task submission/Swayam Prakash BARIK/url.txt
Labels: Task 2, Web Dev, completed

#262 Task 3 completed
  Web Development/Task-1/Task submission/Ritu Rani/SK!LL.png
  Web Development/Task-1/Task submission/Ritu Rani/Web capture_11-5-2021_1585_127.0.0.1.jpeg
  Web Development/Task-1/Task submission/Ritu Rani/css/styles.css
  Web Development/Task-1/Task submission/Ritu Rani/hobbi.png
  Web Development/Task-1/Task submission/Ritu Rani/index.html
  Web Development/Task-1/Task submission/Ritu Rani/int.png
  Web Development/Task-1/Task submission/Ritu Rani/pic.png
  Web Development/Task-1/Task submission/Ritu Rani/profile link.txt
  Web Development/Task-2/riturani/README.md
  Web Development/Task-2/riturani/SK!LL.png
  Web Development/Task-2/riturani/css/styles.css
  Web Development/Task-2/riturani/hobbi.png
  Web Development/Task-2/riturani/index.html
  Web Development/Task-2/riturani/int.png
  Web Development/Task-2/riturani/pic.png
Labels: Task 2, Web Dev, completed

#264 Task3
  Web Development/Task-1/Task submission/Pratham-Mishra/Screenshot.png
  Web Development/Task-1/Task submission/Pratham-Mishra/fonts/font1.ttf
  Web Development/Task-1/Task submission/Pratham-Mishra/fonts/font2.ttf
  Web Development/Task-1/Task submission/Pratham-Mishra/images/interest.png
  Web Development/Task-1/Task submission/Pratham-Mishra/images/pratham.jpg
  Web Development/Task-1/Task submission/Pratham-Mishra/images/skill.png
  Web Development/Task-1/Task submission/Pratham-Mishra/index.html
  Web Development/Task-1/Task submission/Pratham-Mishra/page url.txt
  Web Development/Task-1/Task submission/Pratham-Mishra/style.css
  Web Development/Task-2/Task submission/Pratham-Mishra/Screenshot.png
  Web Development/Task-2/Task submission/Pratham-Mishra/fonts/font1.ttf
  Web Development/Task-2/Task submission/Pratham-Mishra/fonts/font2.ttf
  Web Development/Task-2/Task submission/Pratham-Mishra/images/interest.png
  Web Development/Task-2/Task submission/Pratham-Mishra/images/moon.png
  Web Development/Task-2/Task submission/Pratham-Mishra/images/pratham.jpg
  Web Development/Task-2/Task submission/Pratham-Mishra/images/skill.png
  Web Development/Task-2/Task submission/Pratham-Mishra/images/sun.png
  Web Development/Task-2/Task submission/Pratham-Mishra/index.html
  Web Development/Task-2/Task submission/Pratham-Mishra/page url.txt
  Web Development/Task-2/Task submission/Pratham-Mishra/style.css
Labels: Task 2, Web Dev, completed

#280 Task 3 Completed
  Web Development/Task-1/Task submission/Biswajeet Dehuri/2.jpg
  Web Development/Task-1/Task submission/Biswajeet Dehuri/MyPage.css
  Web Development/Task-1/Task submission/Biswajeet Dehuri/Screenshot 2021-05-13 090858.png
  Web Development/Task-1/Task submission/Biswajeet Dehuri/breach.jpg
  Web Development/Task-1/Task submission/Biswajeet Dehuri/index.html
  Web Development/Task-1/Task submission/Biswajeet Dehuri/link.txt
  Web Development/Task-1/Task submission/Biswajeet Dehuri/logo3.jpg
  Web Development/Task-1/Task submission/Biswajeet Dehuri/logo4.jpg
  Web Development/Task-1/Task submission/Biswajeet Dehuri/ph1.jpg
  Web Development/Task-2/Task submission/Biswajeet Dehuri/2.jpg
  Web Development/Task-2/Task submission/Biswajeet Dehuri/4.jpg
  Web Development/Task-2/Task submission/Biswajeet Dehuri/MyPage.css
  Web Development/Task-2/Task submission/Biswajeet Dehuri/Screenshot 2021-05-15 192622.png
  Web Development/Task-2/Task submission/Biswajeet Dehuri/Screenshot 2021-05-15 192652.png
  Web Development/Task-2/Task submission/Biswajeet Dehuri/breach.jpg
  Web Development/Task-2/Task submission/Biswajeet Dehuri/index.html
  Web Development/Task-2/Task submission/Biswajeet Dehuri/link.txt
  Web Development/Task-2/Task submission/Biswajeet Dehuri/logo3.jpg
  Web Development/Task-2/Task submission/Biswajeet Dehuri/logo4.jpg
  Web Development/Task-2/Task submission/Biswajeet Dehuri/ph1.jpg
  Web Development/Task-2/Task submission/Biswajeet Dehuri/style.js
Labels: Task 2, Web Dev, completed

#265 Task 3 completed
  Web Development/Task-1/Task submission/Dhairya-Joshi/Resources/photo.jpeg
  Web Development/Task-1/Task submission/Dhairya-Joshi/Resources/test.jpg
  Web Development/Task-1/Task submission/Dhairya-Joshi/Screenshot.png
  Web Development/Task-1/Task submission/Dhairya-Joshi/URL.txt
  Web Development/Task-1/Task submission/Dhairya-Joshi/index.css
  Web Development/Task-1/Task submission/Dhairya-Joshi/index.html
  Web Development/Task-2/Task submission/Dhairya-Joshi/Resources/light.png
  Web Development/Task-2/Task submission/Dhairya-Joshi/Resources/photo.jpeg
  Web Development/Task-2/Task submission/Dhairya-Joshi/Resources/test.jpg
  Web Development/Task-2/Task submission/Dhairya-Joshi/URL.txt
  Web Development/Task-2/Task submission/Dhairya-Joshi/index.css
  Web Development/Task-2/Task submission/Dhairya-Joshi/index.html
  Web Development/Task-2/Task submission/Dhairya-Joshi/script.js
Labels: Task 2, Web Dev, completed

#278 Task 3 completed
  Web Development/Task-1/Task submission/Adyasha_Samal1/astro.jpg
  Web Development/Task-1/Task submission/Adyasha_Samal1/bulbOff.jpg
  Web Development/Task-1/Task submission/Adyasha_Samal1/bulbOn.jpg
  Web Development/Task-1/Task submission/Adyasha_Samal1/githubURL.txt
  Web Development/Task-1/Task submission/Adyasha_Samal1/index.html
  Web Development/Task-1/Task submission/Adyasha_Samal1/screenshot.png
  Web Development/Task-1/Task submission/Adyasha_Samal1/style1.css
  Web Development/Task-1/Task submission/shraddha-suman/Screenshot (27).png
  Web Development/Task-1/Task submission/shraddha-suman/index.html
  Web Development/Task-1/Task submission/shraddha-suman/shraddha.txt
  Web Development/Task-2/Task submission/Adyasha_Samal2/DarkBKG.jpg
  Web Development/Task-2/Task submission/Adyasha_Samal2/LightBKG.jpg
  Web Development/Task-2/Task submission/Adyasha_Samal2/bulbOff.jpg
  Web Development/Task-2/Task submission/Adyasha_Samal2/bulbOn.jpg
  Web Development/Task-2/Task submission/Adyasha_Samal2/dark.css
  Web Development/Task-2/Task submission/Adyasha_Samal2/index.html
  Web Development/Task-2/Task submission/Adyasha_Samal2/light.css
  Web Development/Task-2/Task submission/Adyasha_Samal2/style1.css
  Web Development/Task-2/Task submission/Adyasha_Samal2/theme.js
  Web Development/Task-2/Task submission/Adyasha_Samal2/url.txt
Labels: Task 2, Web Dev, completed

#267 https://bisu2580.github.io/About_me
  Web Development/Task-1/Task submission/Biswajit Sahoo/Introduction-Biswajit.png
  Web Development/Task-1/Task submission/Biswajit Sahoo/URL_website.txt
  Web Development/Task-1/Task submission/Biswajit Sahoo/biswa.jpg
  Web Development/Task-1/Task submission/Biswajit Sahoo/index.html
  Web Development/Task-1/Task submission/Biswajit Sahoo/page.css
  Web Development/Task-1/Task submission/Biswajit Sahoo/universe-1800259__340.webp
  Web Development/Task-2/Task submission/Biswajit Sahoo/Before.png
  Web Development/Task-2/Task submission/Biswajit Sahoo/Biswajit_Sahoo.txt
  Web Development/Task-2/Task submission/Biswajit Sahoo/after.png
  Web Development/Task-2/Task submission/Biswajit Sahoo/biswa.jpg
  Web Development/Task-2/Task submission/Biswajit Sahoo/index.html
  Web Development/Task-2/Task submission/Biswajit Sahoo/index.js
  Web Development/Task-2/Task submission/Biswajit Sahoo/page.css
  Web Development/Task-2/Task submission/Biswajit Sahoo/universe-1800259__340.webp
  Web Development/Task-2/Task submission/Biswajit Sahoo/unsplash.jpg
Labels: Task 2, Web Dev, completed

#266 task1
  Web Development/Task-1/Task submission/Shubhrajyoti/My pic.jpeg
  Web Development/Task-1/Task submission/Shubhrajyoti/bg_img.jpg
  Web Development/Task-1/Task submission/Shubhrajyoti/css_file.css
  Web Development/Task-1/Task submission/Shubhrajyoti/index.html
  Web Development/Task-1/Task submission/Shubhrajyoti/ss of my page.png
  Web Development/Task-1/Task submission/Shubhrajyoti/url of my page.txt
  Web Development/Task-2/Task submission/Shubhrajyoti/My pic.jpeg
  Web Development/Task-2/Task submission/Shubhrajyoti/bg_img.jpg
  Web Development/Task-2/Task submission/Shubhrajyoti/css_file.css
  Web Development/Task-2/Task submission/Shubhrajyoti/index.html
  Web Development/Task-2/Task submission/Shubhrajyoti/url of my page.txt
Labels: Task 2, Web Dev, completed

#270 task 3 completed
  Web Development/Task-1/Task submission/Sweta_Padhy/Link.txt
  Web Development/Task-1/Task submission/Sweta_Padhy/css/all.min.css
  Web Development/Task-1/Task submission/Sweta_Padhy/image.jpg
  Web Development/Task-1/Task submission/Sweta_Padhy/index.html
  Web Development/Task-1/Task submission/Sweta_Padhy/screenshot_webpage.png
  Web Development/Task-1/Task submission/Sweta_Padhy/webfonts/fa-brands-400.eot
  Web Development/Task-1/Task submission/Sweta_Padhy/webfonts/fa-brands-400.svg
  Web Development/Task-1/Task submission/Sweta_Padhy/webfonts/fa-brands-400.ttf
  Web Development/Task-1/Task submission/Sweta_Padhy/webfonts/fa-brands-400.woff
  Web Development/Task-1/Task submission/Sweta_Padhy/webfonts/fa-brands-400.woff2
  Web Development/Task-1/Task submission/Sweta_Padhy/webfonts/fa-regular-400.eot
  Web Development/Task-1/Task submission/Sweta_Padhy/webfonts/fa-regular-400.svg
  Web Development/Task-1/Task submission/Sweta_Padhy/webfonts/fa-regular-400.ttf
  Web Development/Task-1/Task submission/Sweta_Padhy/webfonts/fa-regular-400.woff
  Web Development/Task-1/Task submission/Sweta_Padhy/webfonts/fa-regular-400.woff2
  Web Development/Task-1/Task submission/Sweta_Padhy/webfonts/fa-solid-900.eot
  Web Development/Task-1/Task submission/Sweta_Padhy/webfonts/fa-solid-900.svg
  Web Development/Task-1/Task submission/Sweta_Padhy/webfonts/fa-solid-900.ttf
  Web Development/Task-1/Task submission/Sweta_Padhy/webfonts/fa-solid-900.woff
  Web Development/Task-1/Task submission/Sweta_Padhy/webfonts/fa-solid-900.woff2
  Web Development/Task-2/Task submission/Sweta_Padhy/css/all.min.css
  Web Development/Task-2/Task submission/Sweta_Padhy/image.jpg
  Web Development/Task-2/Task submission/Sweta_Padhy/index.html
  Web Development/Task-2/Task submission/Sweta_Padhy/link.txt
  Web Development/Task-2/Task submission/Sweta_Padhy/webfonts/fa-brands-400.eot
  Web Development/Task-2/Task submission/Sweta_Padhy/webfonts/fa-brands-400.svg
  Web Development/Task-2/Task submission/Sweta_Padhy/webfonts/fa-brands-400.ttf
  Web Development/Task-2/Task submission/Sweta_Padhy/webfonts/fa-brands-400.woff
  Web Development/Task-2/Task submission/Sweta_Padhy/webfonts/fa-brands-400.woff2
  Web Development/Task-2/Task submission/Sweta_Padhy/webfonts/fa-regular-400.eot
  Web Development/Task-2/Task submission/Sweta_Padhy/webfonts/fa-regular-400.svg
  Web Development/Task-2/Task submission/Sweta_Padhy/webfonts/fa-regular-400.ttf
  Web Development/Task-2/Task submission/Sweta_Padhy/webfonts/fa-regular-400.woff
  Web Development/Task-2/Task submission/Sweta_Padhy/webfonts/fa-regular-400.woff2
  Web Development/Task-2/Task submission/Sweta_Padhy/webfonts/fa-solid-900.eot
  Web Development/Task-2/Task submission/Sweta_Padhy/webfonts/fa-solid-900.svg
  Web Development/Task-2/Task submission/Sweta_Padhy/webfonts/fa-solid-900.ttf
  Web Development/Task-2/Task submission/Sweta_Padhy/webfonts/fa-solid-900.woff
  Web Development/Task-2/Task submission/Sweta_Padhy/webfonts/fa-solid-900.woff2
Labels: Task 1, Task 2, Web Dev, completed

#276 web dev task-2
  Web Development/Task-1/Task submission/CHANDAN KUMAR HABODA/a85.jpg
  Web Development/Task-1/Task submission/CHANDAN KUMAR HABODA/index.html
  Web Development/Task-1/Task submission/CHANDAN KUMAR HABODA/indexc.css
  Web Development/Task-1/Task submission/CHANDAN KUMAR HABODA/url.txt
Labels: Task 1, Web Dev, completed

#273 task 3
  Web Development/Task-1/Task submission/kareena_sahoo/index.html
  Web Development/Task-1/Task submission/kareena_sahoo/kareena.jpg
  Web Development/Task-1/Task submission/kareena_sahoo/style.css
  Web Development/Task-1/Task submission/kareena_sahoo/url.txt
  Web Development/Task-1/Task submission/kareena_sahoo/website-screenshot.png
  Web Development/Task-2/Task submission/Kareena sahoo/Dark theme.png
  Web Development/Task-2/Task submission/Kareena sahoo/Light theme.png
  Web Development/Task-2/Task submission/Kareena sahoo/index.html
  Web Development/Task-2/Task submission/Kareena sahoo/kareena.jpg
  Web Development/Task-2/Task submission/Kareena sahoo/style.css
  Web Development/Task-2/Task submission/Kareena sahoo/theme.js
  Web Development/Task-2/Task submission/Kareena sahoo/url.txt
Labels: Task 2, Web Dev, completed

#343 Open source task-2 and Web Development task-1 & 2 completed.
  Open Source/Git2/ANINDITA DAS.jpg
  Web Development/Task-1/Task submission/Anindita Das/girl.jpg
  Web Development/Task-1/Task submission/Anindita Das/index.html
  Web Development/Task-1/Task submission/Anindita Das/link.txt
  Web Development/Task-1/Task submission/Anindita Das/web-page.png
  Web Development/Task-2/Task submission/Anindita Das/dark-theme.png
  Web Development/Task-2/Task submission/Anindita Das/girl.jpg
  Web Development/Task-2/Task submission/Anindita Das/index.html
  Web Development/Task-2/Task submission/Anindita Das/light-theme.png
  Web Development/Task-2/Task submission/Anindita Das/link.txt
Labels: Late, Late Git and github, Task 2, Web Dev, completed

#345 web development task 2 completed
  Web Development/Task-2/Task submission/sandeepan/URL.txt
  Web Development/Task-2/Task submission/sandeepan/about me.png
  Web Development/Task-2/Task submission/sandeepan/blue.jpg
  Web Development/Task-2/Task submission/sandeepan/bright ss.png
  Web Development/Task-2/Task submission/sandeepan/dark ss.png
  Web Development/Task-2/Task submission/sandeepan/hobbies.jpg
  Web Development/Task-2/Task submission/sandeepan/imgh.jpg
  Web Development/Task-2/Task submission/sandeepan/index.htm
  Web Development/Task-2/Task submission/sandeepan/java.js
  Web Development/Task-2/Task submission/sandeepan/my interest.jpg
  Web Development/Task-2/Task submission/sandeepan/mystyle.css
  Web Development/Task-2/Task submission/sandeepan/red.jpg
  Web Development/Task-2/Task submission/sandeepan/skills.png
Labels: Late, Task 2, Web Dev, completed

#304 Task3
  Web Development/Task-1/Task submission/NIkhil-Kumar-Sahu/Screenshot (179).png
  Web Development/Task-1/Task submission/NIkhil-Kumar-Sahu/index.html
  Web Development/Task-1/Task submission/NIkhil-Kumar-Sahu/photo.jpg
  Web Development/Task-1/Task submission/NIkhil-Kumar-Sahu/style.css
  Web Development/Task-1/Task submission/NIkhil-Kumar-Sahu/url.txt
  Web Development/Task-2/Task submission/Nikhil-Kumar-Sahu/Screenshot (179).png
  Web Development/Task-2/Task submission/Nikhil-Kumar-Sahu/index.html
  Web Development/Task-2/Task submission/Nikhil-Kumar-Sahu/photo.jpg
  Web Development/Task-2/Task submission/Nikhil-Kumar-Sahu/style.css
  Web Development/Task-2/Task submission/Nikhil-Kumar-Sahu/url.txt
Labels: Task 2, Web Dev, completed

#303 Web Page Task 1 and Task 2
  Web Development/Task-1/Task submission/Asmi-Jena/Asmi.jpg
  Web Development/Task-1/Task submission/Asmi-Jena/Skill-Logo-Type-Check-Chart-Graphics-3681029-1.jpg
  Web Development/Task-1/Task submission/Asmi-Jena/Web page Asmi SS.png
  Web Development/Task-1/Task submission/Asmi-Jena/bg.jpg
  Web Development/Task-1/Task submission/Asmi-Jena/index.html
  Web Development/Task-1/Task submission/Asmi-Jena/interest.jpg
  Web Development/Task-1/Task submission/Asmi-Jena/page-url.txt
  Web Development/Task-1/Task submission/Asmi-Jena/style.css
  Web Development/Task-2/Task submission/Asmi-Jena/Asmi.jpg
  Web Development/Task-2/Task submission/Asmi-Jena/Page SS/Web page light mode SS.png
  Web Development/Task-2/Task submission/Asmi-Jena/Page SS/Web-pg dark mode SS.png
  Web Development/Task-2/Task submission/Asmi-Jena/Skill-Logo-Type-Check-Chart-Graphics-3681029-1.jpg
  Web Development/Task-2/Task submission/Asmi-Jena/bg.jpg
  Web Development/Task-2/Task submission/Asmi-Jena/dkbg.jpg
  Web Development/Task-2/Task submission/Asmi-Jena/index.html
  Web Development/Task-2/Task submission/Asmi-Jena/index.js
  Web Development/Task-2/Task submission/Asmi-Jena/interest.jpg
  Web Development/Task-2/Task submission/Asmi-Jena/page-url.txt
  Web Development/Task-2/Task submission/Asmi-Jena/style.css
Labels: Late, Task 2, Web Dev, completed

#352 WebDev Task1&2
  Web Development/Task-1/Task submission/Ishita-Satpathy/bg.jpg
  Web Development/Task-1/Task submission/Ishita-Satpathy/bluej.png
  Web Development/Task-1/Task submission/Ishita-Satpathy/c.png
  Web Development/Task-1/Task submission/Ishita-Satpathy/css.png
  Web Development/Task-1/Task submission/Ishita-Satpathy/dark mode ss.png
  Web Development/Task-1/Task submission/Ishita-Satpathy/html5.png
  Web Development/Task-1/Task submission/Ishita-Satpathy/index.html
  Web Development/Task-1/Task submission/Ishita-Satpathy/light mode ss.png
  Web Development/Task-1/Task submission/Ishita-Satpathy/link.txt
  Web Development/Task-1/Task submission/Ishita-Satpathy/script.js
  Web Development/Task-1/Task submission/Ishita-Satpathy/style.css
  Web Development/Task-1/Task submission/Ishita-Satpathy/tele dp.jpg
  Web Development/Task-2/Task submission/Ishita-Satpathy/bg.jpg
  Web Development/Task-2/Task submission/Ishita-Satpathy/bluej.png
  Web Development/Task-2/Task submission/Ishita-Satpathy/c.png
  Web Development/Task-2/Task submission/Ishita-Satpathy/css.png
  Web Development/Task-2/Task submission/Ishita-Satpathy/dark mode ss.png
  Web Development/Task-2/Task submission/Ishita-Satpathy/html5.png
  Web Development/Task-2/Task submission/Ishita-Satpathy/index.html
  Web Development/Task-2/Task submission/Ishita-Satpathy/light mode ss.png
  Web Development/Task-2/Task submission/Ishita-Satpathy/link.txt
  Web Development/Task-2/Task submission/Ishita-Satpathy/script.js
  Web Development/Task-2/Task submission/Ishita-Satpathy/style.css
  Web Development/Task-2/Task submission/Ishita-Satpathy/tele dp.jpg
Labels: Late, Task 2, Web Dev, completed

#351 WEB DEV BOTH(1 & 2) TASK'S DONE
  Web Development/Task-1/Task submission/swapnil-kumar-sahu/URL.txt
  Web Development/Task-1/Task submission/swapnil-kumar-sahu/img/1.jpg
  Web Development/Task-1/Task submission/swapnil-kumar-sahu/img/Snapchat-314959173.jpg
  Web Development/Task-1/Task submission/swapnil-kumar-sahu/img/l.png
  Web Development/Task-1/Task submission/swapnil-kumar-sahu/index.html
  Web Development/Task-1/Task submission/swapnil-kumar-sahu/style.css
  Web Development/Task-2/Task submission/swapnil-kumar-sahu(task 2)/Index.html
  Web Development/Task-2/Task submission/swapnil-kumar-sahu(task 2)/URL.txt
  Web Development/Task-2/Task submission/swapnil-kumar-sahu(task 2)/img/1.jpg
  Web Development/Task-2/Task submission/swapnil-kumar-sahu(task 2)/img/Snapchat-314959173.jpg
  Web Development/Task-2/Task submission/swapnil-kumar-sahu(task 2)/img/l.png
  Web Development/Task-2/Task submission/swapnil-kumar-sahu(task 2)/style.css
Labels: Late, Task 2, Web Dev, completed

#342 python task 1
  Python and Ml/Task-1/Task Submission/Dhairya-Joshi/Armstrong-Number.ipynb
  Python and Ml/Task-1/Task Submission/Dhairya-Joshi/Calculator.ipynb
  Python and Ml/Task-1/Task Submission/Dhairya-Joshi/Roots.ipynb
  Python and Ml/Task-1/Task Submission/Dhairya-Joshi/Sorting-words.ipynb
  Python and Ml/Task-1/Task Submission/Dhairya-Joshi/Sum-of-randoms.ipynb
Labels: Python, Task 1, completed

#348 PYTHON TASK 1 COMPLETED
  Python and Ml/Task-1/Task Submission/Suraj/ARMSTRONG_NUMBER.ipynb
  Python and Ml/Task-1/Task Submission/Suraj/CALCULATOR.ipynb
  Python and Ml/Task-1/Task Submission/Suraj/QUADRATIC_EQUATIONS.ipynb
  Python and Ml/Task-1/Task Submission/Suraj/RANDOM_NUMBERS_SUM.ipynb
  Python and Ml/Task-1/Task Submission/Suraj/SORT_WORDS.ipynb
Labels: Python, Task 1, completed

#406 task 1
  Python and Ml/Task-1/Task Submission/sushobhan biswal/q-1.ipynb
  Python and Ml/Task-1/Task Submission/sushobhan biswal/q-2.ipynb
  Python and Ml/Task-1/Task Submission/sushobhan biswal/q-3.ipynb
  Python and Ml/Task-1/Task Submission/sushobhan biswal/q-4.ipynb
  Python and Ml/Task-1/Task Submission/sushobhan biswal/q-5.ipynb
Labels: Python, Task 1, completed

#420 python task 1
  Python and Ml/Task-1/Task Submission/Astha-Niharika/Index.ipynb
  Python and Ml/Task-1/Task Submission/Astha-Niharika/armstrong.ipynb
  Python and Ml/Task-1/Task Submission/Astha-Niharika/dictionary.ipynb
  Python and Ml/Task-1/Task Submission/Astha-Niharika/discriminant.ipynb
  Python and Ml/Task-1/Task Submission/Astha-Niharika/generator.ipynb
Labels: Python, Task 1, completed

#419 Task 1 Submitted python
  Python and Ml/Task-1/Task Submission/Subhranshu-Pradhan/armstrong no.ipynb
  Python and Ml/Task-1/Task Submission/Subhranshu-Pradhan/quadratic equation.ipynb
  Python and Ml/Task-1/Task Submission/Subhranshu-Pradhan/random no sum.ipynb
  Python and Ml/Task-1/Task Submission/Subhranshu-Pradhan/simple calculator.ipynb
  Python and Ml/Task-1/Task Submission/Subhranshu-Pradhan/sorting words.ipynb
Labels: Python, Task 1, completed

#418 Task1 done By Rudramadhaba Mishra
  Python and Ml/Task-1/Task Submission/Rudramadhaba-Mishra/q1 quadratic equation.ipynb
  Python and Ml/Task-1/Task Submission/Rudramadhaba-Mishra/q2 armstrong no.ipynb
  Python and Ml/Task-1/Task Submission/Rudramadhaba-Mishra/q3 simple calculator.ipynb
  Python and Ml/Task-1/Task Submission/Rudramadhaba-Mishra/q4 sorting words.ipynb
  Python and Ml/Task-1/Task Submission/Rudramadhaba-Mishra/q5 random no sum.ipynb
Labels: Python, Task 1, completed

#415 Task 1 Python
  Python and Ml/Task-1/Task Submission/Sangram-Subudhi/Armstrong_Number.ipynb
  Python and Ml/Task-1/Task Submission/Sangram-Subudhi/Generate_Random_Number.ipynb
  Python and Ml/Task-1/Task Submission/Sangram-Subudhi/Quadratic_Equation.ipynb
  Python and Ml/Task-1/Task Submission/Sangram-Subudhi/Simple_Calculator.ipynb
  Python and Ml/Task-1/Task Submission/Sangram-Subudhi/Sorted_Alphabetically.ipynb
Labels: Python, Task 1, completed

#411 Python Task 1
  Python and Ml/Task-1/Task Submission/Adarsh Goswami/1.ipynb
  Python and Ml/Task-1/Task Submission/Adarsh Goswami/2.ipynb
  Python and Ml/Task-1/Task Submission/Adarsh Goswami/3.ipynb
  Python and Ml/Task-1/Task Submission/Adarsh Goswami/4.ipynb
  Python and Ml/Task-1/Task Submission/Adarsh Goswami/5.ipynb
Labels: Python, Task 1, completed

#409 python task1
  Python and Ml/Task-1/Task Submission/Yogesh-Febyani/armstrong.ipynb
  Python and Ml/Task-1/Task Submission/Yogesh-Febyani/calculator.ipynb
  Python and Ml/Task-1/Task Submission/Yogesh-Febyani/quadratic.ipynb
  Python and Ml/Task-1/Task Submission/Yogesh-Febyani/sort alp.ipynb
  Python and Ml/Task-1/Task Submission/Yogesh-Febyani/sum_of_no.ipynb
Labels: Python, Task 1, completed
